name: build

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        name: yarn install
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: yarn test
        with:
          cmd: test

  docker:
    name: Build, test and tag the Docker image
    runs-on: ubuntu-latest
    needs: test
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Read the version
        id: version
        uses: "notiz-dev/github-action-json-property@release"
        with:
          path: "package.json"
          prop_path: "version"
      - name: Read the image repo
        id: image
        uses: "notiz-dev/github-action-json-property@release"
        with:
          path: "package.json"
          prop_path: "image"
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{steps.image.outputs.prop}}:${{steps.version.outputs.prop}}
      - name: Inspect
        run: |
          docker buildx imagetools inspect ${{steps.image.outputs.prop}}:${{steps.version.outputs.prop}}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Check cluster-info
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.0
      - name: Install chart
        run: |
          echo helm upgrade -i instant-search-demo --set image.repository=${{steps.image.outputs.prop}},image.tag=${{steps.version.outputs.prop}} ./contrib/chart/instant-search-demo --wait
      - name: Check pod status
        run: |
          kubectl get pod -n default
