name: build

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        name: yarn install
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: yarn test
        with:
          cmd: test

  docker:
    name: Build, test and tag the Docker image
    runs-on: ubuntu-latest
    needs: test
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: localhost:5000/instant-search-demo:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/instant-search-demo:latest
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Check cluster-info
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (install)
        run: ct install
